##### Data inputs #####
# The reference genome: need to be indexed with bwa index, samtools faidx (.fai), CreateSequenceDictionary (.dict) in the same directory.
# Ideally, the reference genome is soft-masked
reference_genome: "data/ref/CENOSS020000001.1.fasta"

# Tab delimited file containing the following columns:
# ANIMAL ID: Sample Name (this could be the run accession code retrieved from ENA)
# R1 READS: absolute path of R1 reads
# R2 READS: absolute path of R2 reads. If single reads, write "None"
reads: "data/input_data.csv"


# The name of the species for which we are analysing genomic data
species: 'Anodonta_anatina'


##### Parameters setting #####
# Fastp
qualified_quality_phred: 20     # The quality value that a base is qualified. Default 15 means phred quality >= Q15 is qualified, default: 15
unqualified_quality_phred: 40   # How many percents of bases are allowed to be unqualified (0~100). Default 40.
min_length_required: 15             # Reads shorter than length_required will be discarded, default is 15.


# Bwa-mem2
min_score: 30                   # Minimum score to output, default: 30 (-T) 


##### Software paths #####
bin: 
    # FastQC v0.12.1
    fastqc : "fastqc"
    # Fastp v1.3.2
    fastp: "fastp"
    # BWA-MEM2 v2.3
    bwa-mem2 : "bwa-mem2"
    # Samblaster v0.1.26
    samblaster : "samblaster"
    # Samtools v1.23.1
    samtools : "samtools"
    # Bamtools v2.5.3
    bamtools: "bamtools"

