# Author: Chiara Bortoluzzi
# Affiliation: SIB Swiss Institute of Bioinformatics
# Project: SNF project funding
# Last modified: 17 April 2026


import os
import glob
import yaml
from pathlib import Path
from snakemake.exceptions import MissingInputException



##--------------------------------------------------------------------------------------##
## Input files
##--------------------------------------------------------------------------------------##
    
all_reads={}


species_name = config["species"]


# Parsing data reads
with open(config["reads"]) as f:   
    next(f)
    for IDX, line in enumerate(f):
        NAME, R1, R2, PLATEFORM = line.strip().split(',')
        species = R1.split('/')[-3]
    
        # We need to define the prefix directly from the filename because sometimes the NAME of the individual in CSV file does not correspond to the prefix
        # For e.g., NAME could be Sample1 whereas prefix could be SRR123456
        prefix = os.path.basename(R1).replace('.fastq.gz','').replace('.fq.gz', '').replace('_R1', '').replace('.R1', '').replace('_1', '')
    
        # Single-end reads
        all_reads[prefix] = {"idx": IDX, "species": species, "reads":[R1], "plateform": PLATEFORM}

        # Paired-end reads
        if not "None" in R2:
            all_reads[prefix]["reads"].append(R2)

##--------------------------------------------------------------------------------------##
## Rules declaration
##--------------------------------------------------------------------------------------##
    
include:
    "rules/fastqc.rules"

include:
    "rules/fastp.rules"

include:
    "rules/bwa-index.rules"

include:
    "rules/bwa-mem.rules"

include:
    "rules/bamtools.rules"


rule all:
    input:
        # FastQC - paired end (R1 and R2)
        expand("results/{species}/fastqc/{prefix}_1_fastqc.html", zip, prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/fastqc/{prefix}_2_fastqc.zip", zip, prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/fastqc/{prefix}_1_fastqc.html", zip,  prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/fastqc/{prefix}_2_fastqc.zip", zip, prefix = all_reads.keys(), species = config["species"]),
        # Fastp
        expand("results/{species}/fastp/{prefix}_fastp.html", zip, prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/fastp/{prefix}_fastp.json", zip, prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/fastp/{prefix}_1.trim.fastq.gz", zip, prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/fastp/{prefix}_2.trim.fastq.gz", zip, prefix = all_reads.keys(), species = config["species"]),
        # BWA-mem index
        expand(config["reference_genome"] + ".ann"),
        # BWA-mem alignment
        expand("results/{species}/bwa-mem/{prefix}.aln.sort.bam", zip, prefix = all_reads.keys(), species = config["species"]),
        expand("results/{species}/bamtools/{prefix}.aln.sort.bamtools", zip, prefix = all_reads.keys(), species = config["species"])
