# Author: Chiara Bortoluzzi
# Affiliation: SIB Swiss Institute of Bioinformatics
# Project: SNF project funding
# Last modified: 17 April 2026


import os
import glob
import yaml
from pathlib import Path
from snakemake.exceptions import MissingInputException



##--------------------------------------------------------------------------------------##
## Input files
##--------------------------------------------------------------------------------------##
    
all_reads={}

# Parsing data reads
with open(config["reads"]) as f:   
    next(f)
    for IDX, line in enumerate(f):
        NAME, R1, R2, PLATEFORM = line.strip().split(',')
        species = R1.split('/')[-3]
    
        # We need to define the prefix directly from the filename because sometimes the NAME of the individual in CSV file does not correspond to the prefix
        # For e.g., NAME could be Sample1 whereas prefix could be SRR123456
        prefix = os.path.basename(R1).replace('.fastq.gz','').replace('.fq.gz', '').replace('_R1', '').replace('.R1', '').replace('_1', '')
    
        # Single-end reads
        all_reads[prefix] = {"idx": IDX, "species": species, "reads":[R1], "plateform": PLATEFORM}

        # Paired-end reads
        if not "None" in R2:
            all_reads[prefix]["reads"].append(R2)


##--------------------------------------------------------------------------------------##
## Rules declaration
##--------------------------------------------------------------------------------------##
    
include:
    "rules/fastqc.rules"

include:
    "rules/fastp.rules"

include:
    "rules/bwa-index.rules"

include:
    "rules/bwa-mem.rules"

include:
    "rules/bamtools.rules"



rule all:
    input:
        expand("results/{species}/fastqc/{prefix}_fastqc.html", zip, prefix = all_reads.keys(), species=[v["species"] for v in all_reads.values()]),
        expand("results/{species}/fastqc/{prefix}_fastqc.zip",  zip, prefix = all_reads.keys(), species=[v["species"] for v in all_reads.values()]),        
        expand("results/{species}/fastp/{prefix}_fastp.html", zip, prefix = all_reads.keys(), species = [v["species"] for v in all_reads.values()]),
        expand("results/{species}/fastp/{prefix}_fastp.json", zip, prefix = all_reads.keys(), species = [v["species"] for v in all_reads.values()]),
        expand("results/{species}/fastp/{prefix}.trim.fastq.gz", zip, prefix = all_reads.keys(), species = [v["species"] for v in all_reads.values()]),
        expand(config["reference_genome"] + ".ann"),
        expand("results/{species}/bwa-mem/{prefix}.aln.sort.bam", zip, prefix = all_reads.keys(), species = [v["species"] for v in all_reads.values()]),
        expand("results/{species}/bamtools/{prefix}.aln.sort.bamtools", zip, prefix = all_reads.keys(), species = [v["species"] for v in all_reads.values()])(snakemake) ebi-501:workflow-single-end chiarabort
